sudo: required

language: java
jdk:
  - oraclejdk9
  - oraclejdk8

addons:
  sonarcloud:
    organization: w4tracking
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN

notifications:
  email:
    - carlosthe19916@gmail.com
    - shanohl.sist@gmail.com

services:
  - docker

env:
  global:
  - MAVEN_OPTS="-Xms4096m -Xmx4096m"

# Script section
script:
  - mvn clean package
  - sonar-scanner
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
  - mvn clean package -Pdocker

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
